site_name: "Bulder Blog"
site_url: 'http://blog.bulderbank.no/'

site_author: 'Team Bulder'
site_description: 'Blog articles by the team @ Bulder Bank'

repo_name: 'bulderbank/blog'
repo_url: 'https://github.com/bulderbank/blog'

edit_uri: edit/main/docs/

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Wahcome: index.md
  - Cloud:
      - Writing configuration:
          - Intro: cloud/writing-configuration/index.md
          - Principles: cloud/writing-configuration/config-oriented-code.md
          - Terraform example: cloud/writing-configuration/terraform.md
  - MermaidJS: mermaid-test.md

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: red
    accent: blue
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest

plugins:
  - img2fig
  - bootstrap-tables
  - git-revision-date-localized
  - mermaid2:
      arguments:
        theme: 'dark'
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - assets/css/tables.css
  - assets/css/images.css
  - assets/css/dark_theme.css
  #- assets/css/codehilite.css
