site_name: "Bulder Bank Blog"
site_url: 'http://blog.bulderbank.no/'

site_author: 'Team Bulder'
site_description: 'Blog articles by the teams @ Bulder Bank'

repo_name: 'bulderbank/blog'
repo_url: 'https://github.com/bulderbank/blog'

edit_uri: edit/main/docs/

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Home: index.md
  - Android:
      - android/about.md
  - Backend:
      - backend/about.md
  - Cloud:
      - cloud/about.md
      - Writing configuration:
        - Intro: cloud/writing-configuration/intro.md
        - Principles: cloud/writing-configuration/config-oriented-code.md
        - Terraform example: cloud/writing-configuration/terraform.md
  - iOS:
      - ios/about.md
  - Loan:
      - loan/about.md
  - UX:
      - ux/about.md

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: red
    accent: blue
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest

plugins:
  - img2fig
  - bootstrap-tables
  - git-revision-date-localized
  - mermaid2:
      arguments:
        theme: 'dark'
  - search

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  #- assets/css/tables.css
  - assets/css/images.css
  - assets/css/dark_theme.css
  #- assets/css/codehilite.css
