site_name: "Bulder Blog"
site_url: 'http://blog.test.bulderbank.tech/'

site_author: 'Team Bulder'
site_description: 'Lorem Ipsum'

repo_name: 'bulderbank/blog'
repo_url: 'https://github.com/bulderbank/blog'

edit_uri: edit/main/docs/

strict: true # Fail build if there are broken links
docs_dir: docs/

nav:
  - Wahcome: index.md
  - Cloud:
      - Human friendy IaC:
          - Intro: cloud/sensible-iac/intro.md
  - MermaidJS: mermaid-test.md

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: red
    accent: blue
  font:
    text: Source Sans Pro
    code: Source Code Pro

plugins:
  - img2fig
  - bootstrap-tables
  - git-revision-date-localized
  - mermaid2:
      arguments:
        theme: 'dark'

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite

extra_css:
  - assets/css/tables.css
  - assets/css/images.css
  - assets/css/dark_theme.css
  #- assets/css/codehilite.css

extra_javascript:
  - https://github-profile.com/dist/gh-profile-card.min.js